version: "3"

services:
  user_service:
    build: .
    command: python main.py
    ports:
      - "5001:5001"
    restart: unless-stopped
    networks:
      - template-py-services_loki

networks:
  template-py-services_loki:
    external: true
