services:
  otel-collector:
    build:
      context: .
      dockerfile: Dockerfile.otel
    restart: unless-stopped
    ports:
      - "4317:4317" #grpc
      - "4318:4318" #http
    depends_on:
      - loki
  loki:
    build:
      context: .
      dockerfile: Dockerfile.loki
    restart: unless-stopped
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana:11.6.0
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - 3000:3000/tcp
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        EOF
        /run.sh
