[project]
name = "common"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "opentelemetry-exporter-otlp (>=1.33.1,<2.0.0)",
    "opentelemetry-distro (>=0.54b1,<0.55)"
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
