[project]
name = "common_lib"
version = "0.1.0"
description = ""

requires-python = ">=3.13"
dependencies = [
"opentelemetry-exporter-otlp (>=1.33.1,<2.0.0)",
"opentelemetry-distro (>=0.54b1,<0.55)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
